dbt_oracle_test: 
   target: dev
   outputs:
      dev:
         type: oracle
         host: localhost
         user: dbt_test
         pass: dbt_test
         port: 1521
         dbname: xe
         schema: dbt_test
         threads: 4